Repository Kernel360/KFE3_bootup_3P1J, pull requests merged in 2025-06, with the labels that each got.

#2 settings: storybook 설치
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  eslint.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  vitest.config.ts
  vitest.shims.d.ts
Labels: setting

#45 [Feat] 아이콘 컴포넌트 제작 #44
  apps/docs/next.config.ts
  apps/docs/package.json
  apps/web/next.config.ts
  apps/web/package.json
  packages/ui/package.json
  packages/ui/src/icons/AlarmIcon.tsx
  packages/ui/src/icons/BackIcon.tsx
  packages/ui/src/icons/BookMarkIcon.tsx
  packages/ui/src/icons/CalendarIcon.tsx
  packages/ui/src/icons/PinIcon.tsx
  packages/ui/src/icons/ProfileIcon.tsx
  packages/ui/tsconfig.json
  packages/ui/types/svg.d.ts
  pnpm-lock.yaml
Labels: feat

#47 [Refactor] tap, input, button 컨포넌트 리펙토링
  .github/.gitmessage.txt
  package.json
  packages/ui/src/button/BaseButton.tsx
  packages/ui/src/button/CustomButton.tsx
  packages/ui/src/button/index.ts
  packages/ui/src/input/BaseInput.tsx
  packages/ui/src/input/CustomInput.tsx
  packages/ui/src/input/IconInput.tsx
  packages/ui/src/input/icons.tsx
  packages/ui/src/input/index.ts
  packages/ui/src/lib/utils.ts
  packages/ui/src/tabs/BaseTab.tsx
  packages/ui/src/tabs/CustomTab.tsx
  packages/ui/src/tabs/StyledTab.tsx
  packages/ui/src/tabs/index.ts
  packages/ui/src/tabs/tabs.tsx
  packages/ui/src/types/button.types.ts
  packages/ui/src/types/input.types.ts
  packages/ui/src/types/tab.types.ts
  pnpm-lock.yaml
Labels: refactor
